
version: '3.1'
services:
    redis:
        image: "redis:7-alpine"
        container_name: "redis_db"
#        restart: always
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=redis-password
            - REDIS_PORT=6379
            - REDIS_DATABASES=16
    mongo:
        image: "mongo:5"
        container_name: "mongo_db"
#        restart: always
        ports:
#            - "27017:27017"
            - "27018:27018"
        volumes:
            - "./data/mongodb:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo-admin
            MONGO_INITDB_ROOT_PASSWORD: mongo-password
    rabbitmq:
        image: "rabbitmq:3.12-management"
        container_name: "rabbitmq"
#        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=rmq_user
            - RABBITMQ_DEFAULT_PASS=rmq_password
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
        volumes:
            - "./data/rabbitmq:/var/lib/rabbitmq/mnesia"

